UBus.UI.Portal/Models/ErrorViewModel.cs
using System;

namespace UBus.UI.Portal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UBus.UI.Portal/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using UBus.Application.Interfaces;
using UBus.Application.ViewModels;

namespace UBus.UI.Portal.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly IFuncionarioAppService _funcionarioAppService;

        public FuncionarioController(IFuncionarioAppService funcionarioAppService)
        {
            _funcionarioAppService = funcionarioAppService;
        }

        public IActionResult Index()
        {
            return View(_funcionarioAppService.ObterTodos());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(FuncionarioViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            try
            {
                _funcionarioAppService.Register(model);
            }
            catch (Exception)
            {
                return View(model);
            }
            
            return RedirectToAction("Index");
        }
    }
}

UBus.UI.Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UBus.UI.Portal.Models;

namespace UBus.UI.Portal.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UBus.UI.Portal/Controllers/VeiculoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using UBus.Application.Interfaces;

namespace UBus.UI.Portal.Controllers
{
    public class VeiculoController : Controller
    {
        private readonly IVeiculoAppService _veiculoAppService;
        private readonly IRotaAppService _rotaAppService;

        public VeiculoController(IVeiculoAppService veiculoAppService,
                                 IRotaAppService rotaAppService)
        {
            _veiculoAppService = veiculoAppService;
            _rotaAppService = rotaAppService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Rotas = _rotaAppService.ObterTodos().Select(x =>
                            new SelectListItem
                            {
                                Text = $"{x.Origem} - {x.Destino}",
                                Value = x.Id.ToString()
                            });

            return View(_veiculoAppService.ObterTodos());
        }
        
        [HttpPost]
        public IActionResult Index(Guid id)
        {
            ViewBag.Rotas = _rotaAppService.ObterTodos().Select(x =>
                            new SelectListItem
                            {
                                Text = $"{x.Origem} - {x.Destino}",
                                Value = x.Id.ToString()
                            });

            return View(_veiculoAppService.ObterItensAdicionaisPorRota(id));
        }

    }
}

UBus.UI.Portal/Views/Funcionario/Create.cshtml
@model UBus.Application.ViewModels.FuncionarioViewModel
@{
    ViewData["Title"] = "Create";
}

<!-- Default box -->
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Criar funcionário</h3>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="PrimeiroNome" class="control-label"></label>
                        <input asp-for="PrimeiroNome" class="form-control" />
                        <span asp-validation-for="PrimeiroNome" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UltimoNome" class="control-label"></label>
                        <input asp-for="UltimoNome" class="form-control" />
                        <span asp-validation-for="UltimoNome" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Ativo" class="control-label"></label>
                        <input asp-for="Ativo" />
                        <span asp-validation-for="Ativo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input id="submitForm" value="Create" class="btn btn-success" />
                        <a asp-action="Index" class="btn btn-info">Back to List</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {
            $('#submitForm').click(function () {
                var ativo = $('input[name="Ativo"]:checked').length > 0;
                if (ativo == true) {
                    $('#submitForm').submit();
                }
                else {
                    alert('Não é possível adicionar um cliente desativado!');

                }
            });
        });
    </script>
}

UBus.UI.Portal/Views/Funcionario/Index.cshtml
@model IEnumerable<UBus.Application.ViewModels.FuncionarioViewModel>

@{
    ViewData["Title"] = "Index";
}
<!-- Default box -->
<div class="box">
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div>
                    <div class="pull-left">
                        <a asp-action="Create" class="btn btn-primary">
                            <span title="Inserir novo" class="glyphicon glyphicon-plus-sign"></span> Inserir novo
                        </a>
                    </div>
                </div>

                <br />
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.PrimeiroNome)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.UltimoNome)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Ativo)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PrimeiroNome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UltimoNome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Ativo)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>

UBus.UI.Portal/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

UBus.UI.Portal/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

UBus.UI.Portal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

UBus.UI.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UBus Portal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">UBus.UI.Portal</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionário</a></li>
                    <li><a asp-area="" asp-controller="Veiculo" asp-action="Index">Veiculo</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - UBus.UI.Portal</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

UBus.UI.Portal/Views/Veiculo/Index.cshtml
@model IEnumerable<UBus.Application.ViewModels.VeiculoViewModel>

@{
    ViewData["Title"] = "Index";
}

<br />
<div class="jumbotron">
    <form asp-action="Index">

        <div class="col-md-12">
            <h4 class="display-4">Filtrar por rota</h4>
        </div>
        <div class="col-md-4">
            <select class="form-control" asp-items="@(new SelectList(ViewBag.Rotas, "Value", "Text"))" name="Id"></select>
        </div>
        <input type="submit" value="Filtrar" class="btn btn-primary" />
    </form>
</div>

<!-- Default box -->
<div class="box">
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <br />
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Marca)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Modelo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ItensAdicionais)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Marca)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Modelo)
                                </td>
                                <td>
                                    @if (item.ItensAdicionais != null)
                                    {
                                        foreach (var add in item.ItensAdicionais)
                                        {
                                            <text>@add.Nome</text>
                                            <br />
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>